version: 2
jobs:
        build:
                docker:
                        - image: circleci/gcc
                steps:
                        - checkout
                        - run: echo 'Hello world!'
